package:
    title:          Yii2 asset for store.js
    name:           yii2-asset-store-js
    type:           yii2-extension
    keywords:       yii2, asset, store-js
    description:    Yii2 extension is a wrapper for [store.js](https://github.com/marcuswestin/store.js) plugin


require:
    hiqdev/hidev-config:        "*"
    hiqdev/hidev-config-php:    "*"
